server:
  port: 8080
spring:
  application:
    name: userManagement
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/user_management
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        order_inserts: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true