server:
  port: ${RESTAURANT_SERVICE_PORT:8091}
spring:
  application:
    name: restaurant
  datasource:
    username: ${RESTAURANT_POSTGRES_USERNAME}
    url: jdbc:postgresql://localhost:5432/restaurant
    password: ${RESTAURANT_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        order_inserts: true
    hibernate:
      ddl-auto: update
    show-sql: true